setwd("~/unit/RWorkShops/Coint/")
library(urca)
source("sregress.r")
x1.adf <- ur.df(x1, type="trend", selectlags="BIC")
x2.adf <- ur.df(x2, type="trend", selectlags="BIC")
summary(x1.adf)
summary(x2.adf)
x <- cbind(x1,x2)
x.ca <- ca.jo(x, K=2, spec="transitory", type="trace")